# Generated by Django 3.0.6 on 2020-08-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_preview', models.CharField(default='Null preview', max_length=100)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(verbose_name='Date')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('likes', models.IntegerField(null=True)),
                ('views', models.IntegerField(null=True)),
                ('href', models.URLField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('aneks', models.ManyToManyField(to='anek.Anek')),
            ],
        ),
    ]
