# Generated by Django 3.0.6 on 2020-08-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anek',
            name='href',
            field=models.URLField(max_length=1000, null=True, unique=True),
        ),
    ]
